# Generated by Django 4.2.16 on 2026-04-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('detected_language', models.CharField(blank=True, max_length=10)),
                ('translated_text', models.TextField(blank=True)),
                ('source', models.CharField(default='telegram', max_length=50)),
                ('narrative_score', models.FloatField(default=0.0)),
                ('rhetoric_score', models.FloatField(default=0.0)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('verdict', models.CharField(choices=[('safe', 'Безпечно'), ('suspicious', 'Підозрілий'), ('ipso', 'ІПСО')], default='safe', max_length=20)),
                ('detected_narratives', models.JSONField(default=list)),
                ('detected_rhetoric', models.JSONField(default=list)),
                ('similar_narratives', models.JSONField(default=list)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnownNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('demoralization', 'Деморалізація'), ('distrust', 'Підрив довіри'), ('false_equivalence', 'Хибна рівність'), ('panic', 'Паніка та страх'), ('corruption', 'Корупція'), ('military_losses', 'Втрати ЗСУ'), ('western_abandonment', 'Захід зраджує'), ('other', 'Інше')], max_length=30)),
                ('example_texts', models.JSONField(default=list)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to='core.analysisresult')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('correct', 'Правильно'), ('wrong', 'Помилка')], max_length=10)),
                ('chat_id', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.analysisresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
