# Generated by Django 4.2.16 on 2026-04-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knownnarrative',
            options={'ordering': ['category', 'title']},
        ),
    ]
